# Generated by Django 4.0.2 on 2022-04-04 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=1000)),
                ('projectDate', models.DateField(default=datetime.datetime(2022, 4, 4, 21, 12, 8, 287632))),
                ('projectDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=1000)),
                ('sectionDate', models.DateField(default=datetime.datetime(2022, 4, 4, 21, 12, 8, 287632))),
                ('sectionDescription', models.TextField()),
                ('sectionDisplayType', models.CharField(max_length=10)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='apicalls.project')),
            ],
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaDescription', models.CharField(max_length=1000)),
                ('mediaDate', models.DateField(default=datetime.datetime(2022, 4, 4, 21, 12, 8, 288632))),
                ('isVideo', models.BooleanField(default=False)),
                ('mediaFile', models.ImageField(upload_to='Images')),
                ('videoUrl', models.TextField(default='')),
                ('sectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediaContent', to='apicalls.section')),
            ],
        ),
    ]
