# Generated by Django 4.0.2 on 2022-04-04 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='mediaDate',
            field=models.DateField(default=datetime.date(2022, 4, 4)),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectDate',
            field=models.DateField(default=datetime.date(2022, 4, 4)),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionDate',
            field=models.DateField(default=datetime.date(2022, 4, 4)),
        ),
    ]
