# Generated by Django 4.0.2 on 2022-04-17 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0003_alter_mediacontent_mediadate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='mediaDate',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='mediaFile',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectDate',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionDate',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
    ]
