# Generated by Django 4.0.2 on 2022-04-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0004_alter_mediacontent_mediadate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediacontent',
            name='mediaDate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectDate',
        ),
        migrations.RemoveField(
            model_name='section',
            name='sectionDate',
        ),
    ]
