# Generated by Django 4.0.2 on 2022-04-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0005_remove_mediacontent_mediadate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=1000)),
                ('projectDescription', models.TextField(blank=True)),
                ('projectDisplayType', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ArtMediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaDescription', models.CharField(blank=True, max_length=1000)),
                ('isVideo', models.BooleanField(default=False)),
                ('mediaFile', models.ImageField(blank=True, upload_to='artImages')),
                ('videoUrl', models.TextField(default='')),
                ('sectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_media', to='apicalls.artproject')),
            ],
        ),
    ]
