# Generated by Django 4.0.2 on 2022-04-24 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0011_alter_blogsection_options_blogsection_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 6, 11, 44, 752996, tzinfo=utc)),
        ),
    ]
