# Generated by Django 4.0.2 on 2022-05-01 05:43

import apicalls.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0012_alter_blogsection_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(blank=True, max_length=200)),
                ('about_content', models.CharField(blank=True, max_length=1000)),
                ('mediaFile', models.ImageField(blank=True, upload_to=apicalls.models.update_about_filename)),
            ],
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 5, 43, 59, 362688, tzinfo=utc)),
        ),
    ]
