# Generated by Django 4.0.2 on 2022-05-07 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0014_alter_about_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediagroupsection',
            name='mediaDes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 5, 16, 13, 740689, tzinfo=utc)),
        ),
    ]
