# Generated by Django 4.0.2 on 2022-05-08 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0015_mediagroupsection_mediades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 10, 16, 25, 181405, tzinfo=utc)),
        ),
    ]
