# Generated by Django 4.0.2 on 2022-05-27 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0016_alter_blogsection_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 17, 18, 51, 636014, tzinfo=utc)),
        ),
    ]
