# Generated by Django 4.0.2 on 2022-05-29 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apicalls', '0017_alter_blogsection_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 7, 40, 2, 655190, tzinfo=utc)),
        ),
    ]
